services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: meli
      POSTGRES_PASSWORD: meli123
      POSTGRES_DB: meli
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapea el archivo de configuración personalizado
      - ./meli-be/src/main/resources/db/config/postgresql.conf:/etc/postgresql/postgresql.conf
      # Mapea el archivo de autenticación de host
      - ./meli-be/src/main/resources/db/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - meli-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meli -d meli"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ./meli-be
    container_name: meli-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meli
      SPRING_DATASOURCE_USERNAME: meli
      SPRING_DATASOURCE_PASSWORD: meli123
      INIT_SQL_PATH: /app/db/init/init-db.sql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - meli-net

  frontend:
    build:
      context: ./meli-fe
    container_name: meli-frontend
    ports:
      - "4321:4321"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - meli-net

volumes:
  postgres_data:

networks:
  meli-net:
