version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: meli
      POSTGRES_PASSWORD: meli123
      POSTGRES_DB: meli
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meli-net

  backend:
    build:
      context: ./meli-be
    container_name: meli-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meli
      SPRING_DATASOURCE_USERNAME: meli
      SPRING_DATASOURCE_PASSWORD: meli123
    depends_on:
      - postgres
    networks:
      - meli-net

  frontend:
    build:
      context: ./meli-fe
    container_name: meli-frontend
    ports:
      - "4321:4321"
    networks:
      - meli-net

volumes:
  postgres_data:

networks:
  meli-net:
